### ISSUE TITLE
能否创建`LICENSE`文件？

### ISSUE THREAD

**Issue by YDX-2147483647** [lyccyl1/BIT-AI#2]
现在已经明确采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)，但 GitHub 没办法识别。请问能否创建`LICENSE`文件呢？

https://github.com/lyccyl1/BIT-AI/blob/5f555023e089a33feb1ebd75842ae73e8001b6f5/README.md?plain=1#L137-L140

大约不是很困难：在 GitHub 网页上创建文件，文件名填`LICENSE`，会出现`Choose a license template`，然后能直接选。具体可以参考 [Adding a license to a repository - GitHub Docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)。

**Comment by lyccyl1** [comment]
已添加，感谢建议
